### ISSUE TITLE
Fedora groupinstall still possible with Ultramarine Linux?

### ISSUE THREAD

**Issue by globetrotterdk** [Ultramarine-Linux/website#3]
I like using a different DE than the default with the Fedora Jam spin. Perhaps it would be a good idea to add something about whether or not it is still possible to do groupinstalls in Ultramarine, such as:
`$ sudo dnf groupinstall "Audio Production"`
which installs Fedora Jam's various bits. Alternatively, would you be interested in doing a custom Ultramarine audio production version?

**Comment by korewaChino** [comment]
Yes. you can still use DNF groupinstall. In fact that Audio Production group is also in the Ultramarine repos!

**Comment by trobonox** [comment]
I will add a notice about groupinstalls in our wiki/documentation. 
A separate edition is not needed, as we are planning to make these groups more accessible soon with a welcome application that shows up post-install.

**Comment by globetrotterdk** [comment]
Thanks for the replies. I would suggest some sort of area for users to add feedback... For example, I did a Fedora 36 Jam spin install and ran the conversion script to Ultramarine. Everything appears to have worked fantastic. The only blemish was that there is a Fedora icon that still remains in the KDE Kicker menu.

In the context of adding `$ sudo dnf groupinstall "Audio Production"` to Ultramarine, do you recommend the creation of an /etc/security/limits.d/95-jack.conf file with the following content?

`@jackuser  -   rtprio           95
@jackuser  -   memlock     unlimited`

**Comment by matteodev8** [comment]
> Thanks for the replies. I would suggest some sort of area for users to add feedback... For example, I did a Fedora 36 Jam spin install and ran the conversion script to Ultramarine. Everything appears to have worked fantastic. The only blemish was that there is a Fedora icon that still remains in the KDE Kicker menu.
> 
> In the context of adding `$ sudo dnf groupinstall "Audio Production"` to Ultramarine, do you recommend the creation of an /etc/security/limits.d/95-jack.conf file with the following content?
> 
> `@jackuser - rtprio 95 @jackuser - memlock unlimited`

did you try `sudo dnf group install "Audio Production"`?

**Comment by globetrotterdk** [comment]
> did you try `sudo dnf group install "Audio Production"`?
I ran the command (Cutefish version), but have yet to use the audio production group.

BTW, any key command for the Cutefish HUD?

**Comment by trobonox** [comment]
> BTW, any key command for the Cutefish HUD?

I don't think there is any, but you can ask the cutefish developers (if you find out a way how to contact them).

By the way, the issues here are only meant for things directly related to the website, like bugs, typos etc.
If you need more help or want to leave other suggestions you can open an issue in the main repo: https://github.com/Ultramarine-Linux/ultramarine

Closing this issue as the main question about groupinstalls has been answered.
If you need additional support or just want to talk to the team, you can join our Discord server which is linked on the website.
